# Generated by Django 5.2.8 on 2025-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_article_image_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='estado',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('DESARROLLO', 'Desarrollo'), ('BAJA', 'Dado de baja')], default='Desarrollo', max_length=24),
        ),
    ]
